### ISSUE TITLE
Is it possible to custom set a header?

### ISSUE THREAD

**Issue by jcoatgoogle** [googleapis/gax-python#141]
I'm preparing a patch to google-cloud-python. Different APIs interact with grpc in different ways, so I'm looking for guidance on how to do this with the ones that use GAX.

In datastore (at least for GRPC, I need to figure out the right way to do it for http 1.1), my current solution is to modify this line
https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/datastore/google/cloud/datastore/_http.py#L304
to be
```return self._stub.Lookup(request_pb, metadata=[(headerkey, headervalue),])```
(this may not be the best way to do this, but I figure that'd come out in code review...)

I'm curious how to best achieve this with GAX

Thank you!

**Comment by geigerj** [comment]
@jcoatgoogle Just to clarify terminology, we maintain a set of auto-generated gRPC client libraries, GAPIC client libraries. GAX is the runtime dependency of the GAPIC client libraries. GAX itself doesn't contain any special utilities for setting the metadata.

The way you'd do it for [the same method in the GAPIC library](https://github.com/googleapis/api-client-staging/blob/master/generated/python/gapic-google-cloud-datastore-v1/google/cloud/gapic/datastore/v1/datastore_api.py#L141) looks pretty similar to what you're already doing, since GAPIC libraries pass the value of the `metadata` keyword directly through to the gRPC layer.

```
from google.cloud.gapic.datastore.v1 import datastore_api
from google.gax import CallOptions
api = datastore_api.DatastoreApi()
...
api.lookup(project_id, read_options, keys, CallOptions(metadata=[(headerkey, headervalue)]))
```

**Comment by jcoatgoogle** [comment]
Thank you very much -- for the clarification on the terminology, as well as the code example. Very easy!
