### ISSUE TITLE
Support override ADC without passing in a custom channel

### ISSUE THREAD

**Issue by geigerj** [googleapis/gax-python#97]
We should make it easier to override ADC; currently the only possible way to do this is to construct a custom Channel object and pass it in to the API wrapper's constructor.

Java GAX already supports this.

(FYI: @garrettjonesgoogle @tbetbetbe)

**Comment by tbetbetbe** [comment]
Users can already override ADC, the override mechanism is different because the python authentication implementation is different.

- In python, authentication is overridden by passing a [metadata_transformer](https://github.com/googleapis/gax-python/blob/master/google/gax/grpc.py#L90) function.

- Users wishing to perform different authentication simply provide a different metadata_transformer function that provides that credentials they are interested in.

If you are aware of that, and think that there is some other element of ADC that needs please update the bug to clarify.

Otherwise, I recommend closing this, as the required functionality is already supported

**Comment by garrettjonesgoogle** [comment]
The generated api wrapper (e.g. publisher_api.py) does not provide a way to pass in a metadata_transformer to pass on to create_stub.

**Comment by geigerj** [comment]
This should have been filed under the toolkit repo. It should be an easy/superficial GAPIC change. I will close this issue and track there.
